### ISSUE TITLE
ReferenceError: Postgres is not defined

### ISSUE THREAD

**Issue by StrongerProgrammer7** [InnovA2/winston-pg#2]
Maybe I don't understand something, but it seems to me that Postgres should be exported from the library,
but it is not available for export, what am I doing wrong?
_Node.js 18.16.0
npm 9.8.0_

`const { /*there is not Postgres*/}= require('@innova2/winston-pg');`

   new Postgres(
                ^

ReferenceError: Postgres is not defined

**Comment by borisNG** [comment]
try importing PostgresTransport it may solve your problem

**Comment by StrongerProgrammer7** [comment]
Ok, thanks, i will try

**Comment by StrongerProgrammer7** [comment]
Thanks, it's work
