### ISSUE TITLE
Running tsc throws "Type 'typeof TransportStream' is not a constructor function type" error

### ISSUE THREAD

**Issue by toddhalfpenny** [InnovA2/winston-pg#3]
Running tsc throws this error with `esModuleInterop` set to `true`
```
node_modules/@innova2/winston-pg/dist/postgres-transport.d.ts:6:66 - error TS2507: Type 'typeof TransportStream' is not a constructor function type.

6 export declare class PostgresTransport<T = DefaultTable> extends TransportStream {
                                                                   ~~~~~~~~~~~~~~~
Found 1 error in node_modules/@innova2/winston-pg/dist/postgres-transport.d.ts:6
```

Looks like this can be fixed by making the same change as here -  https://github.com/namshi/winston-graylog2/pull/84/commits/24e0b45f2232290c28b5c7bc4447df1920bfc42b - for a similar issue.
I have done this locally and tsc no longer complains.
Happy to raise a PR, if that's better.

**Comment by WaZeR-Adrien** [comment]
Hello, the problem has been fixed in 1.3.1, thanks for your issue ☺️
