### ISSUE TITLE
how to custom timezone?

### ISSUE THREAD

**Issue by shifenhutu** [InnovA2/winston-pg#5]
i want to custom time zone

but  i can't find the way

looks like  the timezone cant change :    https://github.com/InnovA2/winston-pg/blob/main/src/postgres-transport.ts#L152

can you fix it ?

thank you very much

**Comment by WaZeR-Adrien** [comment]
Hello, sorry for my late reply.
I made the change, it's integrated into version 1.4.0 :)

PR merged : https://github.com/InnovA2/winston-pg/pull/6
